// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIS1ba4KVun6Ly5Rh5M8f9p3lTc897Fo4',
    appId: '1:181585246463:web:6b766ff372bc180575f4ca',
    messagingSenderId: '181585246463',
    projectId: 'ikiaralik-34d2b',
    authDomain: 'ikiaralik-34d2b.firebaseapp.com',
    storageBucket: 'ikiaralik-34d2b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnVJ_iD-jBWAMmEMgEcfUtOkHoDBELUzk',
    appId: '1:181585246463:android:aab0f9299ce2563d75f4ca',
    messagingSenderId: '181585246463',
    projectId: 'ikiaralik-34d2b',
    storageBucket: 'ikiaralik-34d2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjBLNIvcCzXhkuZAUD_Ha65wPXIrfd50M',
    appId: '1:181585246463:ios:5c2f8fcafe66e55475f4ca',
    messagingSenderId: '181585246463',
    projectId: 'ikiaralik-34d2b',
    storageBucket: 'ikiaralik-34d2b.appspot.com',
    iosBundleId: 'com.example.ikiaralik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjBLNIvcCzXhkuZAUD_Ha65wPXIrfd50M',
    appId: '1:181585246463:ios:d0ae717a085bda4775f4ca',
    messagingSenderId: '181585246463',
    projectId: 'ikiaralik-34d2b',
    storageBucket: 'ikiaralik-34d2b.appspot.com',
    iosBundleId: 'com.example.ikiaralik.RunnerTests',
  );
}
